name: example
description: Rx Shared Preferences example.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_provider: ^2.0.0
  rx_shared_preferences:

dependency_overrides:
  rx_shared_preferences:
    path: ../
  rx_storage:
    git:
      url: https://github.com/Flutter-Dart-Open-Source/rx_storage.git
      ref: 6b443b544852f57fecb7b2d878f8a171fe3fb665

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
