name: rx_shared_preferences
description: Rxdart streaming shared preferences. Reactive stream rxdart wrapper around SharedPreferences. A stream based wrapper over shared_preferences, allowing reactive key-value storage.
version: 1.3.2
homepage: https://github.com/hoc081098/rx_shared_preferences.git
repository: https://github.com/hoc081098/rx_shared_preferences.git
issue_tracker: https://github.com/hoc081098/rx_shared_preferences/issues

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: '>=0.5.7+3 <2.0.0'
  rxdart: '>=0.24.1 <0.26.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  shared_preferences_platform_interface: ^1.0.4
  collection: ^1.14.11
